remote_theme: "mmistakes/jekyll-theme-basically-basic"

# Site Settings
lang: en-GB
title: EAI - Enterprise Application Integration
email: emanuele.laurenzi@fhnw.ch
description: "This is the portal for the Enterprise Application Integration module."
url: "https://enterprise-application-integration.github.io/"
repository: "enterprise-application-integration.enterprise-application-integration.github.io"
author:
  name: Emanuele Laurenzi
github_username: enterprise-application-integration
logo: 
search: true
search_full_content: true
search_provider: lunr

# Front Matter Defaults
defaults:
